# [dbo].[__EFMigrationsHistory]

In [0]:
USE [notas_php]
GO

In [0]:
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 11/04/2024 7:10:32 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[ArticuloEtiqueta]

In [0]:
/****** Object:  Table [dbo].[ArticuloEtiqueta]    Script Date: 11/04/2024 7:10:32 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ArticuloEtiqueta](
	[Articulo_Id] [int] NOT NULL,
	[Etiqueta_Id] [int] NOT NULL,
 CONSTRAINT [PK_ArticuloEtiqueta] PRIMARY KEY CLUSTERED 
(
	[Etiqueta_Id] ASC,
	[Articulo_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Categoria]

In [0]:
/****** Object:  Table [dbo].[Categoria]    Script Date: 11/04/2024 7:10:32 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[Categoria_Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](max) NULL,
	[Activo] [bit] NOT NULL,
	[FechaCreacion] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[Categoria_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[DetalleUsuario]

In [0]:
/****** Object:  Table [dbo].[DetalleUsuario]    Script Date: 11/04/2024 7:10:32 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DetalleUsuario](
	[DetalleUsuario_Id] [int] IDENTITY(1,1) NOT NULL,
	[Cedula] [nvarchar](max) NOT NULL,
	[Depórte] [nvarchar](max) NOT NULL,
	[Mascota] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_DetalleUsuario] PRIMARY KEY CLUSTERED 
(
	[DetalleUsuario_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Etiqueta]

In [0]:
/****** Object:  Table [dbo].[Etiqueta]    Script Date: 11/04/2024 7:10:32 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Etiqueta](
	[Etiqueta_Id] [int] IDENTITY(1,1) NOT NULL,
	[Titulo] [nvarchar](max) NULL,
	[Fecha] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Etiqueta] PRIMARY KEY CLUSTERED 
(
	[Etiqueta_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[notas]

In [0]:
/****** Object:  Table [dbo].[notas]    Script Date: 11/04/2024 7:10:32 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[notas](
	[idnota] [int] IDENTITY(1,1) NOT NULL,
	[titulo] [nvarchar](50) NULL,
	[descripcion] [nvarchar](200) NULL,
	[fecha] [date] NOT NULL,
	[usuario_id] [int] NULL,
 CONSTRAINT [PK_notas] PRIMARY KEY CLUSTERED 
(
	[idnota] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Tbl_Articulo]

In [0]:
/****** Object:  Table [dbo].[Tbl_Articulo]    Script Date: 11/04/2024 7:10:32 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Articulo](
	[Articulo_Id] [int] IDENTITY(1,1) NOT NULL,
	[Articulo] [nvarchar](20) NOT NULL,
	[Descripcion] [nvarchar](50) NOT NULL,
	[Calificacion] [nvarchar](max) NULL,
	[Fecha] [datetime2](7) NOT NULL,
	[Categoria_Id] [int] NOT NULL,
 CONSTRAINT [PK_Tbl_Articulo] PRIMARY KEY CLUSTERED 
(
	[Articulo_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[usuario]

In [0]:
/****** Object:  Table [dbo].[usuario]    Script Date: 11/04/2024 7:10:32 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuario](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[email] [nvarchar](max) NULL,
	[Nombre] [nvarchar](max) NULL,
	[Direccion] [nvarchar](max) NULL,
	[DetalleUsuario_Id] [int] NOT NULL,
 CONSTRAINT [PK_usuario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[__EFMigrationsHistory]

In [0]:
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20240409023328_inicial', N'6.0.0')
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20240409025827_crearEtiqueta', N'6.0.0')
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20240409032242_relacionMuchosAMuchos', N'6.0.0')
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20240410022926_AgregarCamposCategoria', N'6.0.0')
GO

# [dbo].[Categoria]

In [0]:
SET IDENTITY_INSERT [dbo].[Categoria] ON 
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1, N'Categoria 1', 1, CAST(N'2024-04-09T21:39:25.2466667' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (2, N'Categoria 2', 1, CAST(N'2024-04-09T21:39:28.3900000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (3, N'Categoria 3', 1, CAST(N'2024-04-09T21:39:31.5333333' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (4, N'Categoria 4', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1002, N'9730ab6e-459d-4f95-a4d3-5e26d2d794f0', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1003, N'a49b42eb-ea02-43fa-870e-e50336984271', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1004, N'0046cb92-3e8f-40e3-b1e8-7abca9596fe9', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1005, N'dbbaf837-85f5-49fd-8e16-ef1644fd55f4', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1006, N'67269920-4755-4eb6-8cf9-7536011ed77c', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1007, N'f425e2c8-f458-45e8-b353-be68cbabcc47', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1008, N'8d531c4e-949c-4f87-b170-da524dc9a2b9', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1009, N'Valor formulario 1', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1010, N'Valor formulario 2', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1011, N'Valor formulario 3', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1012, N'Valor formulario 4', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
INSERT [dbo].[Categoria] ([Categoria_Id], [Nombre], [Activo], [FechaCreacion]) VALUES (1013, N'Valor formulario 5', 0, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
SET IDENTITY_INSERT [dbo].[Categoria] OFF
GO

# [DF__Categoria__Activ__01142BA1]

In [0]:
ALTER TABLE [dbo].[Categoria] ADD  DEFAULT (CONVERT([bit],(0))) FOR [Activo]
GO

# [DF__Categoria__Fecha__02084FDA]

In [0]:
ALTER TABLE [dbo].[Categoria] ADD  DEFAULT ('0001-01-01T00:00:00.0000000') FOR [FechaCreacion]
GO

# [FK_ArticuloEtiqueta_Etiqueta_Etiqueta_Id]

In [0]:
ALTER TABLE [dbo].[ArticuloEtiqueta]  WITH CHECK ADD  CONSTRAINT [FK_ArticuloEtiqueta_Etiqueta_Etiqueta_Id] FOREIGN KEY([Etiqueta_Id])
REFERENCES [dbo].[Etiqueta] ([Etiqueta_Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ArticuloEtiqueta] CHECK CONSTRAINT [FK_ArticuloEtiqueta_Etiqueta_Etiqueta_Id]
GO

# [FK_ArticuloEtiqueta_Tbl_Articulo_Articulo_Id]

In [0]:
ALTER TABLE [dbo].[ArticuloEtiqueta]  WITH CHECK ADD  CONSTRAINT [FK_ArticuloEtiqueta_Tbl_Articulo_Articulo_Id] FOREIGN KEY([Articulo_Id])
REFERENCES [dbo].[Tbl_Articulo] ([Articulo_Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ArticuloEtiqueta] CHECK CONSTRAINT [FK_ArticuloEtiqueta_Tbl_Articulo_Articulo_Id]
GO

# [FK_Tbl_Articulo_Categoria_Categoria_Id]

In [0]:
ALTER TABLE [dbo].[Tbl_Articulo]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_Articulo_Categoria_Categoria_Id] FOREIGN KEY([Categoria_Id])
REFERENCES [dbo].[Categoria] ([Categoria_Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Tbl_Articulo] CHECK CONSTRAINT [FK_Tbl_Articulo_Categoria_Categoria_Id]
GO

# [FK_usuario_DetalleUsuario_DetalleUsuario_Id]

In [0]:
ALTER TABLE [dbo].[usuario]  WITH CHECK ADD  CONSTRAINT [FK_usuario_DetalleUsuario_DetalleUsuario_Id] FOREIGN KEY([DetalleUsuario_Id])
REFERENCES [dbo].[DetalleUsuario] ([DetalleUsuario_Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[usuario] CHECK CONSTRAINT [FK_usuario_DetalleUsuario_DetalleUsuario_Id]
GO